In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,4]
type(l)

list

In [4]:
np.array(l)

array([1, 2, 3, 4, 4])

In [5]:
a = np.array(l)
type(a)

numpy.ndarray

In [7]:
a1 = np.array([[1,2,3], [3,4,5]])
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [8]:
a2 = np.array([[[1,2,3], [3,4,5]]])
a2

array([[[1, 2, 3],
        [3, 4, 5]]])

In [9]:
a.ndim

1

In [10]:
a1.ndim

2

In [11]:
a2.ndim

3

In [12]:
a3 = np.array([[[1,2,3], [3,4,5]],[[1,2,3], [3,4,5]],[[1,2,3], [3,4,5]]])

In [13]:
a3

array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]]])

In [14]:
l = [1, 2, 3, 4]
np.asarray(l)

array([1, 2, 3, 4])

In [15]:
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [16]:
#Matix hold 2 dimention minimum.


In [17]:
a = np.asarray(l)
a1 = a

In [18]:
a

array([1, 2, 3, 4])

In [19]:
a1

array([1, 2, 3, 4])

In [20]:
a[0]=10
a

array([10,  2,  3,  4])

In [21]:
a1

array([10,  2,  3,  4])

In [22]:
#Here changes are refecting in even in a1.

In [23]:
a2 = np.copy(a)
a2

array([10,  2,  3,  4])

In [24]:
a2[2]=30
a2

array([10,  2, 30,  4])

In [25]:
a

array([10,  2,  3,  4])

In [26]:
#in copy sitiutaion it won't reflect the chnages.
#These are examples fo deep copy and shallow copy.
#First example where values are reflecting was shallow copy and the second one is deep copy

In [27]:
np.fromfunction(lambda i,j : i == j, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [28]:
np.random.rand(2,3)

array([[0.27488815, 0.59633074, 0.49304658],
       [0.60424536, 0.15585634, 0.90401922]])

In [29]:
np.random.rand(2,3,2)

array([[[0.84288067, 0.42642599],
        [0.83116516, 0.73939381],
        [0.79418128, 0.63468371]],

       [[0.6252667 , 0.0941475 ],
        [0.35225107, 0.83189995],
        [0.38222527, 0.96122037]]])

In [30]:
np.random.rand(2,3,3)

array([[[0.59367891, 0.83144688, 0.23119271],
        [0.25356128, 0.00513993, 0.83969433],
        [0.28993226, 0.27175721, 0.61632945]],

       [[0.73925524, 0.70883758, 0.13534795],
        [0.32132838, 0.84313647, 0.19779691],
        [0.09708719, 0.4330866 , 0.76848885]]])

In [31]:
np.random.rand(1,4,4)

array([[[0.06837373, 0.05989989, 0.27193936, 0.60855237],
        [0.87018128, 0.08987277, 0.64566695, 0.32110796],
        [0.50434639, 0.55297261, 0.58598372, 0.48355634],
        [0.59525858, 0.08180931, 0.9163907 , 0.5538974 ]]])

In [32]:
np.random.rand(3,4,4)

array([[[0.0584268 , 0.26051895, 0.99580325, 0.34027673],
        [0.22852835, 0.4133239 , 0.37878718, 0.21934045],
        [0.08244043, 0.39326197, 0.85890592, 0.96484853],
        [0.88383828, 0.77511138, 0.44208132, 0.31817694]],

       [[0.78816585, 0.3791208 , 0.31581765, 0.86454891],
        [0.32261516, 0.27584905, 0.87530978, 0.39541318],
        [0.0313703 , 0.42506795, 0.23859449, 0.05212996],
        [0.84685094, 0.01207511, 0.92731796, 0.21256662]],

       [[0.58755355, 0.0828317 , 0.09482806, 0.92575678],
        [0.31040212, 0.61033784, 0.87355663, 0.50764087],
        [0.08181123, 0.47863011, 0.58243698, 0.16648294],
        [0.71824865, 0.49706526, 0.17121695, 0.4432942 ]]])

In [33]:
np.random.randn(3,4,4)

array([[[ 0.92181428,  1.02389369,  0.69920751, -0.28155807],
        [ 0.14484651,  1.70111596,  1.31614373,  0.49281282],
        [-0.62027441,  0.30895527,  0.7442131 ,  0.95143342],
        [ 1.61240166, -0.427536  , -1.57598012, -0.00454571]],

       [[ 0.6302487 ,  0.06572511,  0.92198966, -1.30620664],
        [-0.32329593,  0.89287934,  0.7055655 , -0.17703773],
        [-0.81610278, -0.24491863,  0.29665484,  0.3424949 ],
        [ 0.66413562,  1.04000034,  0.97575532,  0.67511155]],

       [[ 1.02371751,  0.14141814, -0.82966026,  2.3129006 ],
        [ 0.00814888,  0.72418299,  0.08860157, -0.29721303],
        [-1.25701703,  1.07802952,  0.72247424, -0.76274922],
        [-1.32658235, -1.16674876, -0.45871782, -0.15693204]]])

In [34]:
#randn follow genereate the data with standarf normal distribution where mean =0 and s.d.=1

In [35]:
np.random.randint(1,10,(4,4))

array([[2, 6, 6, 7],
       [5, 2, 6, 4],
       [2, 7, 1, 6],
       [3, 7, 9, 1]])

In [36]:
np.random.randint(1,10,(4,4,2))

array([[[6, 5],
        [3, 1],
        [2, 7],
        [1, 8]],

       [[3, 8],
        [3, 7],
        [8, 4],
        [8, 4]],

       [[5, 7],
        [5, 2],
        [7, 8],
        [7, 6]],

       [[3, 5],
        [9, 2],
        [7, 7],
        [5, 9]]])

In [39]:
d = np.random.randn(3,4)
d

array([[-0.23480795,  0.55090726, -0.78135043,  1.32746621],
       [ 0.30433326,  0.3816616 , -0.4114391 , -1.06745669],
       [ 1.59852781,  1.271292  ,  0.15711585,  1.60981634]])

In [40]:
import pandas as pd
pd.DataFrame(d)

0         1         2         3
0 -0.234808  0.550907 -0.781350  1.327466
1  0.304333  0.381662 -0.411439 -1.067457
2  1.598528  1.271292  0.157116  1.609816

In [41]:
d1 = np.random.randint(1,10,(4,4,2))
pd.DataFrame(d1)

ValueError: Must pass 2-d input. shape=(4, 4, 2)

In [42]:
d1.reshape(16, 2)

array([[8, 3],
       [1, 8],
       [2, 8],
       [4, 3],
       [1, 5],
       [1, 1],
       [6, 5],
       [7, 6],
       [5, 8],
       [2, 4],
       [8, 1],
       [1, 2],
       [9, 5],
       [5, 3],
       [3, 8],
       [9, 7]])

In [43]:
d1.reshape(8, 4)

array([[8, 3, 1, 8],
       [2, 8, 4, 3],
       [1, 5, 1, 1],
       [6, 5, 7, 6],
       [5, 8, 2, 4],
       [8, 1, 1, 2],
       [9, 5, 5, 3],
       [3, 8, 9, 7]])

In [44]:
d1.reshape(10, 2)

ValueError: cannot reshape array of size 32 into shape (10,2)

In [45]:
d1.reshape(8, -1)

array([[8, 3, 1, 8],
       [2, 8, 4, 3],
       [1, 5, 1, 1],
       [6, 5, 7, 6],
       [5, 8, 2, 4],
       [8, 1, 1, 2],
       [9, 5, 5, 3],
       [3, 8, 9, 7]])

In [46]:
#here neagative values automatically chcek for missing multiplication of dimention. it will same for all neagative values.
#negative value is just placefolder.

In [47]:
pd.DataFrame(d1.reshape(8, -1))

0  1  2  3
0  8  3  1  8
1  2  8  4  3
2  1  5  1  1
3  6  5  7  6
4  5  8  2  4
5  8  1  1  2
6  9  5  5  3
7  3  8  9  7

In [48]:
#Real time example of 3D to 2D is coversion of colourful image to B/W image as colurful image hold the RGB matrix.