In [1]:
import pandas as pd
import numpy as np

In [2]:
range(10)

range(0, 10)

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(3, 9))

[3, 4, 5, 6, 7, 8]

In [5]:
list(range(3, 10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
#Range function only take the interger as upper, lower bound and range.

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(.5, 10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [9]:
np.arange(5, -4, -1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [10]:
np.arange(5, -4, -.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])